<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="SayHelloService"
     targetNamespace="http://single/"
     xmlns:ns1="http://single/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="SayHello_PL">
        <plnk:role name="SayHello_Role">
            <plnk:portType name="ns1:SayHello"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://single/" location="sayhello.wsdl"/>
</wsdl:definitions>
